name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@https://github.com/canonical/observability/tree/scenario-snapshot-on-itest-failure
    secrets: inherit